volumes:
  postgres-data:
    external: true
services:
  postgres:
    image: postgres:14.5-bullseye
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: example_user
      POSTGRES_DB: example
    ports:
      - 15432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  fastapi:
    build:
      context: sample_service
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - ./sample_service:/app
    environment:
      DATABASE_URL: postgresql://example_user:secret@postgres/example
      WAIT_HOSTS: postgres:5432
    env_file:
      - .env

  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: http://localhost:3000
      REACT_APP_SAMPLE_SERVICE_API_HOST: http://localhost:8000
